### ISSUE TITLE
Slow to draw client

### ISSUE THREAD

**Issue by emersion** [emersion/wleird#1]
Add a client that is very slow to draw.

**Comment by kennylevinsen** [comment]
Define - is a sleep in a render implementation good enough? If so, is it to stall the entire event loop or is it just to make reactions to things like configure very slow?

**Comment by emersion** [comment]
The original intent was a client that makes replying to configure events slow.

**Comment by emersion** [comment]
This is addressed by https://github.com/emersion/wleird/pull/16
