### ISSUE TITLE
SIGBUS client

### ISSUE THREAD

**Issue by malcolmstill** [emersion/wleird#12]
- Client generates SIGBUS by claiming buffer is larger than it is or truncating

**Comment by emersion** [comment]
Which client? Can you obtain a stack trace?

**Comment by malcolmstill** [comment]
@emersion sorry I wasn't clear in the issue.

What I meant was that I was suggesting a new client for inclusion in `wleird` that intentionally causes a SIGBUS (for testing non-libwayland compositors)

**Comment by emersion** [comment]
Oh. Yeah, that's a good idea.

**Comment by malcolmstill** [comment]
I've not got this in a state ready to be included in `wleird` but a tiny modification of [`hello-wayland`](https://github.com/emersion/hello-wayland) provokes a SIGBUS: https://github.com/malcolmstill/hello-wayland/tree/malcolm/provoke-sigbus
