### ISSUE TITLE
Intended resizor behavior

### ISSUE THREAD

**Issue by vyivel** [emersion/wleird#24]
In Weston, the surface is anchored to its bottom-right corner during resizing. In Sway/KWin, it's anchored to its top-left corner. Considering that there is code to change the surface buffer position, Weston's approach seems right, though an idea of Wayland clients being able to change their position feels weird to me.

Which behavior is the correct/intended one? Or is it up to compositors to decide?

**Comment by emersion** [comment]
Anchoring to bottom-right is the expected behaviour.
