### ISSUE TITLE
Prefix binary names (similar to weston test clients)

### ISSUE THREAD

**Issue by rmader** [emersion/wleird#32]
This repo looks like a lovely collection of handy tools :heart: 
I just find the names hard to discover (if installed to `/usr/local/bin` / launched via `PATH` as I usually do for test clients, so I can do it in a guest session).

I'd love to see the binary names prefix by something like `wleird-`, just as the Weston test clients have the `weston-` prefix - that makes the full list easy to discover. Mind doing so or would you accept a MR for that?

**Comment by emersion** [comment]
Sure, feel free to send a patch!
